# Generated by Django 3.2.5 on 2021-07-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snacks',
            old_name='eater',
            new_name='purchaser',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='rank',
        ),
    ]
